# Generated by Django 4.1.4 on 2022-12-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='desc',
            new_name='description',
        ),
    ]
